task/urls.py
from django.urls import path
from . import views


app_name = "task"

urlpatterns = [
    path("score/", views.TaskScoreView.as_view(), name="score"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("daily/", views.TaskDailyView.as_view(), name="daily"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.TaskUpdateView.as_view(), name="update"),
    path("api/<int:pk>/delete/", views.TaskDeleteAPIView.as_view(), name="delete-api"),
    path("<int:pk>/delete/", views.TaskDeleteView.as_view(), name="delete"),
]

taskapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls"), name="account"),
    path("task/", include("task.urls"), name="task"),
]

task/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Task(models.Model):
    TASK_TYPE_MOST_IMPORTANT = "Most Important"
    TASK_TYPE_CRITICAL = "Critical"
    TASK_TYPE_OTHER = "Other"
    TASK_TYPES = (TASK_TYPE_MOST_IMPORTANT, TASK_TYPE_CRITICAL, TASK_TYPE_OTHER)
    TASK_DUERATION_DAILY = "Daily"
    TASK_DUERATION_LONG_SHORT_TERM = "Long-Short term"
    TASK_DUERATIONS = (TASK_DUERATION_DAILY, TASK_DUERATION_LONG_SHORT_TERM)
    is_completed = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    description = models.TextField()
    deadline = models.DateTimeField()
    created_by = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="tasks"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    score = models.IntegerField(default=1)
    type = models.CharField(
        max_length=20,
        choices=((i, i) for i in TASK_TYPES),
        default=TASK_TYPE_MOST_IMPORTANT,
    )
    duration = models.CharField(
        max_length=20,
        choices=((i, i) for i in TASK_DUERATIONS),
        default=TASK_DUERATION_LONG_SHORT_TERM,
    )

    def __str__(self):
        return self.name

task/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            format="%Y-%m-%dT%H:%M", attrs={"type": "datetime-local"}
        )
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        # add form-control class for bootstrap and add placeholder
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    def save(self, commit=True):
        task = super().save(commit=False)
        task.created_by = self.request.user
        duration = self.request.GET.get("duration")
        if duration not in Task.TASK_DUERATIONS:
            duration = Task.TASK_DUERATION_LONG_SHORT_TERM
        task.duration = duration
        if commit:
            task.save()
        return task

    class Meta:
        model = Task
        fields = ["name", "description", "deadline", "type"]

task/views.py
from django.core.paginator import Paginator
from django.http import Http404
from django.utils import timezone
from django.shortcuts import render, redirect
from django.views import View
from django.db.models import Sum
from task.forms import TaskForm
from task.models import Task
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist

TASK_MODEL_FIELDS_NAME = [field.name for field in Task._meta.fields]


def get_redirect_url(duration):
    """
    Get redirect url from task.
    """
    return "task:daily" if duration == Task.TASK_DUERATION_DAILY else "task:list"


def get_data_to_search(data, exclude_fields=[]):
    return {
        d: data[d]
        for d in data
        if d.split("__")[0] in TASK_MODEL_FIELDS_NAME
        and d.split("__")[0] not in exclude_fields
    }  # noqa


def check_field_in_search_dict(field, search_dict):
    return any([field in f for f in search_dict])


def get_field_in_search_dict(field, search_dict):
    for f in search_dict:
        if field in f:
            return search_dict[f]


class TaskCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = TaskForm(request=request)
        return render(request, "task/create-task.html", {"form": form})

    def post(self, request):
        form = TaskForm(request.POST, request=request)
        if form.is_valid():
            form.save()
            return redirect(get_redirect_url(form.instance.duration))
        return render(request, "task/create-task.html", {"form": form})


class TaskScoreView(LoginRequiredMixin, View):
    template_name = "task/task-score.html"

    def get(self, request):
        data = request.GET.dict()
        from_ = data.pop("from", None)
        to = data.pop("to", None)
        data_to_search = get_data_to_search(data, ["duration"])
        tasks = request.user.tasks.filter(
            **data_to_search, duration=Task.TASK_DUERATION_DAILY
        ).distinct()
        if from_ and to:
            tasks = tasks.filter(created_at__date__gte=from_, created_at__date__lte=to)
        tasks_score = (
            tasks.filter(is_completed=True)
            .values("created_at__date")
            .annotate(score=Sum("score"))
            .values("created_at__date", "score")
            .order_by("created_at__date")
        )
        paginator = Paginator(tasks_score, 50)
        page = data.get("page", 1)
        tasks_score = paginator.get_page(page)
        context = {
            "tasks_score": tasks_score,
            "task_types": Task.TASK_TYPES,
        }
        return render(request, self.template_name, context)


class TaskListView(LoginRequiredMixin, View):
    template_name = "task/task-list.html"

    def get(self, request):
        data = request.GET.dict()
        data_to_search = get_data_to_search(data, ["duration"])
        tasks = request.user.tasks.filter(
            **data_to_search, duration=Task.TASK_DUERATION_LONG_SHORT_TERM
        ).distinct()  # noqa
        tasks = tasks.order_by("-id").values(
            "id", "name", "deadline", "type", "is_completed"
        )
        paginator = Paginator(tasks, 10)
        page = data.get("page", 1)
        tasks = paginator.get_page(page)
        context = {
            "tasks": tasks,
            "task_types": Task.TASK_TYPES,
        }
        return render(request, self.template_name, context)


class TaskDailyView(LoginRequiredMixin, View):
    template_name = "task/task-daily.html"

    def get(self, request):
        data = request.GET.dict()
        data_to_search = get_data_to_search(data, ["duration"])
        if not check_field_in_search_dict("created_at", data_to_search):
            data_to_search["created_at__date"] = timezone.now().date()
        tasks = (
            request.user.tasks.filter(
                **data_to_search, duration=Task.TASK_DUERATION_DAILY
            )
            .distinct()
            .order_by("-id")
        )  # noqa
        score = tasks.values("is_completed").annotate(all_score=Sum("score"))
        earned_score = total_score = 0
        if score.exists():
            earned_score_qs = score.filter(is_completed=True)
            if earned_score_qs.exists():
                earned_score = earned_score_qs.last()["all_score"]
            total_score = score.aggregate(total_score=Sum("all_score"))["total_score"]

        context = {
            "tasks": tasks.order_by("deadline").values(
                "id", "name", "deadline", "is_completed", "type"
            ),
            "total_score": total_score,
            "earned_score": earned_score,
            "created_at": timezone.datetime.strptime(
                str(get_field_in_search_dict("created_at", data_to_search)), "%Y-%m-%d"
            ),  # noqa
        }
        return render(request, self.template_name, context)


class TaskDetailView(LoginRequiredMixin, View):
    template_name = "task/task-detail.html"

    def get(self, request, pk):
        try:
            task = request.user.tasks.get(pk=pk)
        except ObjectDoesNotExist:
            raise Http404
        return render(request, self.template_name, {"task": task})

    def post(self, request, pk):
        try:
            task = request.user.tasks.get(pk=pk)
        except ObjectDoesNotExist:
            raise Http404
        task.is_completed = not task.is_completed
        task.save(update_fields=["is_completed"])
        return JsonResponse(
            {"message": "Successfully Marked!", "is_completed": task.is_completed},
            status=200,
        )


class TaskUpdateView(LoginRequiredMixin, View):
    template_name = "task/create-task.html"

    def get(self, request, pk):
        try:
            task = request.user.tasks.get(pk=pk)
        except ObjectDoesNotExist:
            raise Http404
        form = TaskForm(instance=task, request=request)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        try:
            task = request.user.tasks.get(pk=pk)
        except ObjectDoesNotExist:
            raise Http404
        form = TaskForm(request.POST, instance=task, request=request)
        if form.is_valid():
            form.save()
            return redirect(get_redirect_url(task.duration))
        return render(request, self.template_name, {"form": form})


class TaskDeleteAPIView(LoginRequiredMixin, View):
    def post(self, request, pk):
        try:
            task = request.user.tasks.get(pk=pk)
        except ObjectDoesNotExist:
            raise Http404
        task.delete()
        return JsonResponse({"success": True})


class TaskDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        try:
            task = request.user.tasks.get(pk=pk)
        except ObjectDoesNotExist:
            raise Http404
        duration = task.duration
        task.delete()
        return redirect(get_redirect_url(duration))

templates/task/create-task.html
{% extends 'base.html' %}
{% block content %}
<section class="main_form">
    <div class="container">
        <div class="row">
              <div class="col-lg-5 col-md-6 col-sm-8 mx-auto">    
                  <div class="row form">
                      {% include 'components/alerts.html' %}
                      <form method='POST'>
                          {% csrf_token %}
                          <h3>Create Task</h3>
                          {{form.as_p}}
                          <button type="submit" class="main_btn">CREATE TASK</button>
                      </form>
                  </div>
              </div>
       </div>
    </div>
</section>
{% endblock content %}

templates/task/task-daily.html
{% extends 'base.html' %}
{% load task_tags %}
{% block content %}
<div class="todo-app">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-sm-12 mx-auto todo-box">
        <div class="single-content">
          <div
            class="header-container d-flex justify-content-between align-items-center"
          >
          <div class="task">
            <h5><a class="simple-anchor" href="?">Total score: {{ total_score }}</a></h5>
            <h5><a class="simple-anchor" href="?is_completed=1">Your score: {{ earned_score }}</a></h5>
          </div>
            <div class="app-day">
              <h2>{{ created_at | date:"l" }}, <span>{{ created_at.day | day_with_postfix }}</span></h2>
              <p>{{ created_at | date:"F"  }}</p>
              <p><strong>{{ tasks.count }} tasks</strong></p>

            </div>
          </div>
          <div class="input-field">
           <a href="{% url 'task:create' %}?duration=Daily"> <button type="button">Add</button></a>
          </div>
            <div class="todo-list">
            
          {% for task in tasks %}
            <div class="d-flex justify-content-between align-items-center mb-5">
              <div class="d-flex justify-content-sent align-items-center">
                <input type="checkbox" name="task-{{task.id}}" />
                
                <h5 class="mb-0">
                  <a href="{% url 'task:detail' task.id %}" class="simple-anchor">
                    {% if task.is_completed %}
                    <i class="fa-solid fa-check-circle fa-lg" style="color: green"></i>
                    {% else %}
                    <i class="fa-solid fa-clock fa-lg" style="color: red;"></i>
                    {% endif %} {{ task.name }} 
                </a><a class="simple-anchor" href="{% url 'task:update' task.id %}?duration=Daily"><i class="fas fa-edit"></i></a></h5>
              </div>
              <p class="time">{{ task.deadline.time }}</p>
            </div>
          {% endfor %}
          </div>
        </div>
            <!--<div>
              <button type="button" class="btn btn-success" style="width:100%; border-radius:0px">Save</button> 
            </div>-->
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}
{% block script %}
<script>
    $(document).ready(function(){
        $('.delete-task-btn').on('click', function(){
            if(confirm('Are you sure you want to delete this task?')){
                var task_id = $(this).attr('task-id');
                var url = $(this).attr('url');
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        'task_id': task_id,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function(data){
                        $('#task-row-' + task_id).remove();
                    }
                });
            }
        });
    });
    function get_tasks(filter){
        var val = $('#deadline_input').val()
        if(val){
            window.location.href = `?deadline__date${filter}=${val}`;
        }
    }
</script>
{% endblock script %}

templates/task/task-detail.html
{% extends 'base.html' %}
{% block content %}
<section class="detail">
    <div class="container">
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="row">
                    <div class="col-lg-10 col-md-10 col-sm-10 col-12 px-3 card_box mx-auto">
                        <div class='row alert' style="display:None;" id="messages">
                        </div>
                        <div class="card_content">
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Name:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.name }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Description:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.description }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Deadline:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.deadline }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Type:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.type }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Score:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.score }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Is Completed:</b>
                                </div>
                                <div class='col-md-8' id="is-completed">
                                    {% if task.is_completed %}Yes {% else %} No{% endif %}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Created at:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.created_at }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-4'>
                                    <b>Updated at:</b>
                                </div>
                                <div class='col-md-8'>
                                    {{ task.updated_at }}
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-md-12 d-flex justify-content-center'>
                                    <button class='add-new-task-btn bg-blue btn-primary p-2 m-3' id="mark-as-btn">
                                        Mark as {% if task.is_completed %}Pending{% else %} Completed{% endif %} </button>
                                    <form method="POST" action="{% url 'task:delete' task.id %}">
                                        {% csrf_token %}
                                        <button class='add-new-task-btn btn btn-danger p-2 m-3' type="submit">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block script %}
<script>
    $(document).ready(function(){
        $('#mark-as-btn').click(function(){
            var data = {
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
            };
            var _this = $(this)
            $.ajax({
                url: '{% url 'task:detail' task.id %}',
                type: 'POST',
                data: data,
                success: function(response){
                    let message = $('#messages')
                    message.html(response.message);
                    if (response.is_completed) {
                        _this.text('Mark as Pending')
                        $("#is-completed").html('Yes')
                    } else {
                        _this.text('Mark as Completed')
                        $("#is-completed").html('No')
                    }
                    message.addClass('alert-success');
                    message.css('display', 'block');
                    setTimeout(function(){
                        message.css('display','None');
                    }, 3000) ;
                }
            });
        });
    });
</script>
{% endblock script %}

templates/task/task-list.html
{% extends 'base.html' %}
{% load task_tags %}

{% block head %}
<style>
.simple-anchor {
    text-decoration: none;   
    color: #000; 
}

</style>
{% endblock head %}
{% block content %}
<div class="container">
    <div class="row mt-3 pt-3" style="background-color: #eeeeee">
        <div class="card-group">
            {% csrf_token %}
            {% for stat in stats %}
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card m-2">
                    <div class="card-body">
                        <a href="?status={{ stat.status }}" style="text-decoration:none; color:black">
                            <h6 class="card-title">{{ stat.status }}</h6>
                            <p class="card-text blue-text"><span class="ml-2" style="font-size: 30px;">{{ stat.count }}</span></p>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title">
                Deadline
            </div>
                <div class="row">
                    <div class='col-lg-8 col-mb-8 col-sm-12 d-flex justify-content-center mb-3'>
                        <input type="date" class='form-control' id="deadline_input" required/>&nbsp;
                        <button type="button" onclick="get_tasks('')" class="btn btn-primary"><i class="fas fa-search"></i></button>&nbsp;
                        <button type="button" class="btn btn-primary" onclick="get_tasks('__gt')"><i class="fa-solid fa-arrow-up"></i></button>&nbsp;
                        <button type="button" class="btn btn-primary" onclick="get_tasks('__lt')"><i class="fa-solid fa-arrow-down"></i></button>
                    </div>
                    <div class='col-lg-4 col-md-4 col-sm-12 d-flex justify-content-end mb-3'>
                        <a href="{% url 'task:create' %}?duration=Long-Short term"><button type="button" class="add-new-task-btn bg-blue"><i class="fa-solid fa-plus me-2"></i>Add New</button></a>
                    </div>
                </div>
        </div>
    </div>
</div>

<div class=" pt-4 pb-4 container">
    <div class="card p-4">
    <ul class="nav nav-tabs">
        <li class="nav-item">
        </li>
        <li class="nav-item">
            <a href="#all" class="nav-link active simple-anchor" style="color:black !important;" data-bs-toggle="tab">All</a>
        </li>
        {% for task_type in task_types %}
            <li class="nav-item">
                <a href="#tab-{{ task_type | text_normailze }}" style="color:black !important;" class="nav-link simple-anchor" data-bs-toggle="tab">{{task_type}}</a>
            </li>
        {% endfor %}
        
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="all">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Task</th>
                        <th>Action</th>
                    </tr>
                    {% for task in tasks %}
                    <tr id="task-row-{{task.id}}">
                        <td>
                            <a href="{% url 'task:detail' task.id %}" class="simple-anchor" title="Status: {{task.status}}">
                                {% if task.is_completed %}
                                <i class="fa-solid fa-check-circle fa-lg" style="color: green"></i>
                                {% else %}
                                <i class="fa-solid fa-clock fa-lg" style="color: red;"></i>
                                {% endif %}  {{ task.name }} | {{ task.type }} | {{ task.deadline }}</a>
                        </td>
                        <td>
                            <span><a href="{% url 'task:update' task.id %}?duration=Long-Short term"><i class="fa-solid fa-pen-to-square me-3" style="font-size:30px; color:black;"></i></a></span>
                            <span task-id={{ task.id }} url="{% url 'task:delete-api' task.id %}" class='delete-task-btn'><i class="fa-solid fa-trash-can me-3" style="font-size:30px; color:black;"></i></span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% group_by tasks 'type' as tasks_by_task_type %}
        {% for type, tasks in tasks_by_task_type.items %}
            <div class="tab-pane fade" id="tab-{{ type | text_normailze }}">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Task</th>
                            <th>Action</th>
                        </tr>
                        {% for task in tasks %}
                        <tr id="task-row-{{task.id}}">
                            <td>
                                <a href="{% url 'task:detail' task.id %}" class="simple-anchor">
                                    {% if task.is_completed %}
                                    <i class="fa-solid fa-check-circle fa-lg" style="color: green"></i>
                                    {% else %}
                                    <i class="fa-solid fa-clock fa-lg" style="color: red;"></i>
                                    {% endif %}  {{ task.name }} | {{ task.deadline }}</a>
                            </td>
                            <td>
                                <span><a href="{% url 'task:update' task.id %}?duration=Long-Short term"><i class="fa-solid fa-pen-to-square me-3" style="font-size:30px; color:black;"></i></a></span>
                                <span task-id={{ task.id }} url="{% url 'task:delete-api' task.id %}" class='delete-task-btn'><i class="fa-solid fa-trash-can me-3" style="font-size:30px; color:black;"></i></span>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
        {% for task_type in task_types %}
        <!--When all task type not found in task_group.grouper-->
        <div class="tab-pane fade" id="tab-{{ task_type | text_normailze }}">
        </div>
        {% endfor %}
        {% load i18n %}
        
        {% if tasks.has_other_pages %}
        <div class="btn-group" role="group" aria-label="Item pagination">
            {% if tasks.has_previous %}
                <a href="?page={{ tasks.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
            {% endif %}
    
            {% for page_number in tasks.paginator.page_range %}
                {% if tasks.number == page_number %}
                    <button class="btn btn-outline-primary active">
                        <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                    </button>
                {% else %}
                    <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                        {{ page_number }}
                    </a>
                {% endif %}
            {% endfor %}
    
            {% if tasks.has_next %}
                <a href="?page={{ tasks.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
            {% endif %}
        </div>
        {% endif %}
        

    </div>
</div>
</div>
</div>

{% endblock content %}
{% block script %}
<script>
    $(document).ready(function(){
        $('.delete-task-btn').on('click', function(){
            if(confirm('Are you sure you want to delete this task?')){
                var task_id = $(this).attr('task-id');
                var url = $(this).attr('url');
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        'task_id': task_id,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function(data){
                        $('#task-row-' + task_id).remove();
                    }
                });
            }
        });
    });
    function get_tasks(filter){
        var val = $('#deadline_input').val()
        if(val){
            window.location.href = `?deadline__date${filter}=${val}`;
        }
    }
</script>
{% endblock script %}

templates/task/task-score.html
{% extends 'base.html' %}
{% load task_tags %}
{% load i18n %}

{% block head %}
<style>
.simple-anchor {
    text-decoration: none;   
    color: #000; 
}

</style>
{% endblock head %}
{% block content %}
<div class="container pt-4">
  
    <div class="card">
        <div class="card-body m-2">
            <div class="row">
                <div class='col-lg-5 col-md-5 col-sm-12 d-flex justify-content-end mb-3'>
                    <label for="from" class="p-2">From: </label>
                    <input type="date" class='form-control' id="from" required/>&nbsp;
                </div>
                <div class='col-lg-5 col-md-5 col-sm-12 d-flex justify-content-end mb-3'>
                    <label for="to" class="p-2">To: </label>
                    <input type="date" class='form-control' id="to" required/>&nbsp;
                </div>
                <div class='col-lg-2 col-md-2 col-sm-12 d-flex justify-content-end mb-3'>
                    <button type="button" onclick="get_tasks()" class="btn btn-primary"><i class="fas fa-search"></i></button>&nbsp;
                </div>
            </div>
        </div>
    </div>
</div>

<div class=" pt-4 pb-4 container">
    <div class="card p-4">
       
        <table class="table">
            <tbody>
                <tr> 
                    <th>Date</th>
                    <th>Score</th>
                </tr>
                {% for task in tasks_score %}
                <tr >
                    <td>
                        {{task.created_at__date}}
                    </td>
                    <td>
                        <a href="{% url 'task:daily' %}?created_at__date={{task.created_at__date|date:'Y-m-d'}}" style="text-decoration:none">{{task.score}}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!--When all task type not found in task_group.grouper-->
    </div>

    {% if tasks_score.has_other_pages %}
    <div class="btn-group" role="group" aria-label="Item pagination">
        {% if tasks_score.has_previous %}
            <a href="?page={{ tasks_score.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        {% for page_number in tasks_score.paginator.page_range %}
            {% if tasks_score.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                    {{ page_number }}
                </a>
            {% endif %}
        {% endfor %}

        {% if tasks_score.has_next %}
            <a href="?page={{ tasks_score.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
</div>
</div>
</div>

{% endblock content %}
{% block script %}
<script>
    function get_tasks(){
        var from = $('#from').val()
        var to = $('#to').val()
        if(from && to){
            window.location.href = `?from=${from}&to=${to}`;
        }
    }
</script>
{% endblock script %}