account/urls.py
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
]

task/urls.py
from django.urls import path
from . import views


app_name = "task"

urlpatterns = [
    path("score/", views.TaskScoreView.as_view(), name="score"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("daily/", views.TaskDailyView.as_view(), name="daily"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.TaskUpdateView.as_view(), name="update"),
    path("api/<int:pk>/delete/", views.TaskDeleteAPIView.as_view(), name="delete-api"),
    path("<int:pk>/delete/", views.TaskDeleteView.as_view(), name="delete"),
]

taskapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls"), name="account"),
    path("task/", include("task.urls"), name="task"),
]

templates/components/alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button class="close" type="button" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags|title }}:
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} 
        <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/components/footer.html
<section class="footer">
    <p>copyright 2022 © by Task Manager</p>
</section>

templates/components/navbar.html
<div class="nav_bar">
    <div class="logo">
      <h1>Task Manager</h1>
    </div>
    <div class="nav_item">
      <div class="cancel-btn">
        <i class="fa-solid fa-xmark"></i>
      </div>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'task:score' %}" {% if '/score' in request.path %}class="active"{% endif %}>Score History</a>
        </li>
        <li>
          <a href="{% url 'task:daily' %}" {% if '/daily' in request.path %}class="active"{% endif %}>Daily Tasks</a>
        </li>
        <li>
          <a href="{% url 'task:list' %}" {% if '/task/list' in request.path %}class="active"{% endif %}>Short-long term Tasks</a>
        </li>
        <a href="{% url 'account:logout' %}" class="button button-red">LOGOUT</a>
        {% else %}
        <a href="{% url 'account:login' %}" class="button button-green">SIGN IN</a>
        {% endif %}
      </ul>
    </div>
    <div class="menu-btn">
      <i class="fa-solid fa-bars"></i>
    </div>
  </div>